-- ==========================================
-- E-commerce Sales Analysis
-- SQL Business Queries
-- Author: Cassius Martins
-- ==========================================


-- Query 1: Receita Total da Empresa
SELECT SUM(QUANTIDADE * PRECO_UNITARIO) AS RECEITA_TOTAL
FROM ITENS_PEDIDO;


-- Query 2: Ticket Médio dos Pedidos
SELECT ROUND(AVG(VALOR_TOTAL), 2) AS TICKET_MEDIO
FROM PEDIDOS;


-- Query 3: Receita por Categoria
SELECT C.NOME_CATEGORIA,
       SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS RECEITA_TOTAL
FROM CATEGORIAS C
INNER JOIN PRODUTOS P
        ON C.ID_CATEGORIA = P.ID_CATEGORIA
INNER JOIN ITENS_PEDIDO I
        ON P.ID_PRODUTO = I.ID_PRODUTO
GROUP BY C.NOME_CATEGORIA
ORDER BY RECEITA_TOTAL DESC;


-- Query 4: Top 5 Clientes por Valor Gasto
SELECT C.NOME,
       SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS TOTAL_GASTO
FROM CLIENTES C
INNER JOIN PEDIDOS P
        ON C.ID_CLIENTE = P.ID_CLIENTE
INNER JOIN ITENS_PEDIDO I
        ON P.ID_PEDIDO = I.ID_PEDIDO
GROUP BY C.NOME
ORDER BY TOTAL_GASTO DESC
FETCH FIRST 5 ROWS ONLY;


-- Query 5: Top 5 Produtos por Faturamento
SELECT P.NOME_PRODUTO,
       SUM(I.QUANTIDADE * I.PRECO_UNITARIO) AS RECEITA_TOTAL
FROM PRODUTOS P
INNER JOIN ITENS_PEDIDO I
        ON P.ID_PRODUTO = I.ID_PRODUTO
GROUP BY P.NOME_PRODUTO
ORDER BY RECEITA_TOTAL DESC
FETCH FIRST 5 ROWS ONLY;


-- Query 6: Pedidos por Mês
SELECT EXTRACT(MONTH FROM DATA_PEDIDO) AS MES,
       COUNT(ID_PEDIDO) AS TOTAL_PEDIDOS
FROM PEDIDOS
GROUP BY EXTRACT(MONTH FROM DATA_PEDIDO)
ORDER BY MES ASC;


-- Query 7: Status dos Pedidos
SELECT STATUS_PEDIDO,
       COUNT(ID_PEDIDO) AS TOTAL_PEDIDOS
FROM PEDIDOS
GROUP BY STATUS_PEDIDO
ORDER BY TOTAL_PEDIDOS DESC;


-- Query 8: Métodos de Pagamento Mais Utilizados
SELECT METODO_PAGAMENTO,
       COUNT(METODO_PAGAMENTO) AS TOTAL_USOS
FROM PAGAMENTOS
GROUP BY METODO_PAGAMENTO
ORDER BY TOTAL_USOS DESC;


-- Query 9: Produtos Sem Venda
SELECT P.NOME_PRODUTO
FROM PRODUTOS P
LEFT JOIN ITENS_PEDIDO I
       ON P.ID_PRODUTO = I.ID_PRODUTO
WHERE I.ID_PRODUTO IS NULL;


-- Query 10: Clientes Recorrentes (Mais de 2 Pedidos)
SELECT C.NOME,
       COUNT(P.ID_PEDIDO) AS TOTAL_PEDIDOS
FROM CLIENTES C
INNER JOIN PEDIDOS P
        ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.NOME
HAVING COUNT(P.ID_PEDIDO) > 2
ORDER BY TOTAL_PEDIDOS DESC;